# Generated by Django 4.0.4 on 2022-06-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafe',
            old_name='varierdad',
            new_name='variedad',
        ),
        migrations.AlterField(
            model_name='vino',
            name='fecha',
            field=models.IntegerField(),
        ),
    ]
