# Generated by Django 4.0.4 on 2022-06-08 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0002_rename_varierdad_cafe_variedad_alter_vino_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vino',
            name='fecha',
            field=models.DateField(),
        ),
    ]
