# Generated by Django 4.0.4 on 2022-06-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0003_alter_vino_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='platos',
            name='receta',
            field=models.TextField(default='Sin receta'),
            preserve_default=False,
        ),
    ]
